# Generated by Django 3.2 on 2022-09-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
